### PR TITLE
update version number for California minor release

### PR DESCRIPTION
**Pull request by tingyuz**
Signed-off-by: Tingyu Zeng <tingyu.zeng@rsa.com>

### CODE REVIEW

**Comment by JPWKU** [comment]
@tingyuz I changed the target branch to california instead of master.

**Comment by JPWKU** [comment]
Can you do a `git checkout feature/update-version-number && git fetch --all --tags && git rebase upstream/california`

**Comment by tingyuz** [comment]
yes I didn't realize that it needs to be changed as well. Thanks.

**Comment by JPWKU** [comment]
then push again to your PR branch

**Comment by tingyuz** [comment]
ran the commands and pushed it again.

**Pull request merged**
