### PR TITLE
Use long sha to reduce chance of collision

### PR DESCRIPTION
**Pull request by JPWKU**
Signed-off-by: Jeremy Phelps <jphelps@linuxfoundation.org>

### CODE REVIEW

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
recheck

**Comment by JPWKU** [comment]
@tingyuz Can you take a look at these build failures again? 
"""
19:58:35 cd core && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -o  edgexproxy .
19:58:41 # github.com/edgexfoundry/security-api-gateway/core
19:58:41 ./main.go:33:25: not enough arguments in call to logger.NewClient
19:58:41 	have (string, bool, string)
19:58:41 	want (string, bool, string, string)
19:58:41 make: *** [build] Error 2
19:58:41 Build step 'Execute shell' marked build as failure
''"

**Comment by anonymouse64** [comment]
@JPWKU that issue is fixed in my PR #27

**Comment by JPWKU** [comment]
@anonymouse64 I thought that it had been fixed...and my branch is fully synced with master...any ideas why this is popping up?

**Comment by JPWKU** [comment]
caveat, this master fix is less important that delhi atm

**Comment by JPWKU** [comment]
@anonymouse64 nm I see....I still need more coffee

**Comment by tingyuz** [comment]
Close this one as it has been addressed in the master branch.

**Pull request closed without merging**
